### ISSUE TITLE
Heltun touchpanel driver

### ISSUE THREAD

**Issue by GoodbyeHarmony** [syepes/Hubitat#2]
Thanks for the hard work!

I have a 2 button version of this.

The driver here doesn't do anything at all and I feel I've done something stupid? It's not recognising a 2 button device at all?

I'm sure it's my misunderstanding!

Thank you Sebastian

**Comment by syepes** [comment]
Great, the same driver should work but it will just need some modifications.
Please follow the below steps and send me the full logs (attachment) so I can analyze them and adapt the driver.

1. Open one browser window with the device stetting page
2. Open another independent window with the live logs (/logs)
3. From the device stetting page set the Log level (Preferences) to **trace**
4. Click on the **Clear State** (Commands) from the device driver
5. Click on the **Refresh** (Commands) from the device driver
6. Now from the live logs page copy all the logs info a notepad file. (Wait 1 or 2 minutes so the Hub receives all the information)
7.  Make a screen capture of the **State Variables** (From the device stetting page)
8. Make a screen capture of the **Device Details** (From the device stetting page)

Please send me by email or attachment all the information from steps 6,7 and 8.

Regards,
Seb

**Comment by GoodbyeHarmony** [comment]
Sorry Sebastian, thank you for your kind and considerate answer. Today has been very busy at work and I have not had chance to reply. I will collect the data you need this evening and send it to you.

Thanks for your help it’s really appreciated

Cheers and stay safe
Tim

**Comment by syepes** [comment]
This device is also now natively supported by HE
