### ISSUE TITLE
Eurotronic Air Quality Sensor - VOC

### ISSUE THREAD

**Issue by mindtripper** [syepes/Hubitat#4]
Looks like I got things partially wrong, but found the solution :)

It is PPB not PPM. But the VOC-Level is in the thousands. Which will never be a reality.

Changing the values to the below will correctly display VOC-level:

```
      if (map.value < 0.065) {
        result << createEvent(name: "VOC-Level", value: "Outstanding", displayed: true)
      } else if (map.value < 0.220) {
        result << createEvent(name: "VOC-Level", value: "Good", displayed: true)
      } else if (map.value < 0.660) {
        result << createEvent(name: "VOC-Level", value: "Mediocre", displayed: true)
      } else if (map.value < 2.200) {
        result << createEvent(name: "VOC-Level", value: "Bad", displayed: true)
      } else if (map.value < 5.500) {
        result << createEvent(name: "VOC-Level", value: "Harmful", displayed: true)

```

Can the driver be user configurable to show PPM or PPB?

---------------------------------------------------------------------------

Disregard below:
Driver works very well, but is it displaying/calculating VOC PPM wrong?
Value in example below show 0.173. Should it not be 173? I.e. be multiplied by 1000?
VOC-level is always Outstanding :)

Example below.
```
Current States
DewPoint : 6.3
HomeHealth : Good
VOC : 0.173
VOC-Level : Outstanding
carbonDioxide : 514
carbonDioxide-Level : Good
humidity : 28.60
temperature : 26.00
```

**Comment by syepes** [comment]
Looking at the specs VOC is in ppb I have adjust it it
<img width="541" alt="image" src="https://user-images.githubusercontent.com/333081/191355785-0d7ab3f7-5d21-4e34-9057-0dc6063315ce.png">
