### ISSUE TITLE
HPM always believes there is an update for the Netamo Velux app

### ISSUE THREAD

**Issue by edasque** [syepes/Hubitat#8]
Maybe something wrong with the app versions in the file or the manifest file at https://github.com/syepes/Hubitat/blob/master/Apps/Netatmo/Netatmo%20-%20Velux.json ?

**Comment by edasque** [comment]
Unfortunately that didn't work, must have missed something, @syepes - I'll dig further

```
Updates found specificdriver for https://raw.githubusercontent.com/syepes/Hubitat/master/Apps/Netatmo/Netatmo%20-%20Velux.json -> Netatmo - Velux - Window (force production: true)
Updates found specificdriver for https://raw.githubusercontent.com/syepes/Hubitat/master/Apps/Netatmo/Netatmo%20-%20Velux.json -> Netatmo - Velux - Shutter (force production: true)
```

**Comment by syepes** [comment]
> Unfortunately that didn't work, must have missed something, @syepes - I'll dig further
> 
> ```
> Updates found specificdriver for https://raw.githubusercontent.com/syepes/Hubitat/master/Apps/Netatmo/Netatmo%20-%20Velux.json -> Netatmo - Velux - Window (force production: true)
> Updates found specificdriver for https://raw.githubusercontent.com/syepes/Hubitat/master/Apps/Netatmo/Netatmo%20-%20Velux.json -> Netatmo - Velux - Shutter (force production: true)
> ```

I'll have a look

**Comment by edasque** [comment]
Did you ever figure it out?
